/**
 * Created by ash on 22/05/2017.
 */
export const SEARCH_ARTICLE_REQUEST = 'SEARCH_ARTICLE_REQUEST';
export const SEARCH_ARTICLE_SUCCESS = 'SEARCH_ARTICLE_SUCCESS';
export const SEARCH_ARTICLE_FAILURE = 'SEARCH_ARTICLE_FAILURE';

export const GET_CHARTER_LIST_REQUEST = 'GET_CHARTER_LIST_REQUEST';
export const GET_CHARTER_LIST_SUCCESS = 'GET_CHARTER_LIST_SUCCESS';
export const GET_CHARTER_LIST_FAILURE = 'GET_CHARTER_LIST_FAILURE';

export const GET_CHARTER_CONTENT_REQUEST = 'GET_CHARTER_CONTENT_REQUEST';
export const GET_CHARTER_CONTENT_SUCCESS = 'GET_CHARTER_CONTENT_SUCCESS';
export const GET_CHARTER_CONTENT_FAILURE = 'GET_CHARTER_CONTENT_FAILURE';

export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';

export const CHANGE_TOOL_SETTING = 'CHANGE_TOOL_SETTING';

export const SET_ARTICLE_LINK = 'SET_ARTICLE_LINK';
